# Generated by Django 4.1 on 2023-10-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dokter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pasien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RekamMedis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kondisi_kesehatan", models.TextField()),
                (
                    "suhu_tubuh",
                    models.DecimalField(decimal_places=1, default=36.0, max_digits=4),
                ),
                ("resep", models.FileField(upload_to="resep/")),
                (
                    "dokter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rekam_medis_app.dokter",
                    ),
                ),
                (
                    "pasien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rekam_medis_app.pasien",
                    ),
                ),
            ],
        ),
    ]
